-- Run this once in Supabase SQL Editor.
--
-- Adds the Widerrufsbelehrung (EU right-of-withdrawal notice) as a new
-- standalone legal page, same admin-editable Content system as your
-- other legal pages. Based on the official German model text (Muster-
-- Widerrufsbelehrung, Anlage 1/2 EGBGB) adapted with your business
-- details from the Impressum. Section 3 specifically covers why
-- personalized products (like letter molds) are excluded from returns —
-- worth a lawyer's look before go-live, same as your other legal pages.

insert into site_content (page_key, field_key, label, field_type, value_de, value_en, sort_order) values

('widerruf', 'eyebrow', 'Small label above the title', 'text', 'Rechtliches', 'Legal', 1),
('widerruf', 'title', 'Page title', 'text', 'Widerrufsbelehrung', 'Right of Withdrawal', 2),

('widerruf', 's1_heading', 'Section 1 — heading', 'text', '1. Widerrufsrecht', '1. Right of withdrawal', 3),
('widerruf', 's1_body', 'Section 1 — body', 'textarea',
'Du hast das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen.<br><br>Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag, an dem du oder ein von dir benannter Dritter, der nicht der Beförderer ist, die Waren in Besitz genommen hast bzw. hat.<br><br>Um dein Widerrufsrecht auszuüben, musst du uns (Artiza Studio, Inh. Nithi Prabhanand, Hinterbergstr. 17, 65207 Wiesbaden, E-Mail: info@artizastudio.de) mittels einer eindeutigen Erklärung (z.&nbsp;B. ein mit der Post versandter Brief oder eine E-Mail) über deinen Entschluss, diesen Vertrag zu widerrufen, informieren. Du kannst dafür das unten stehende Muster-Widerrufsformular verwenden, das jedoch nicht vorgeschrieben ist.<br><br>Zur Wahrung der Widerrufsfrist reicht es aus, dass du die Mitteilung über die Ausübung des Widerrufsrechts vor Ablauf der Widerrufsfrist absendest.',
'You have the right to withdraw from this contract within fourteen days without giving any reason.<br><br>The withdrawal period is fourteen days from the day on which you, or a third party named by you who is not the carrier, took possession of the goods.<br><br>To exercise your right of withdrawal, you must inform us (Artiza Studio, owner Nithi Prabhanand, Hinterbergstr. 17, 65207 Wiesbaden, Germany, email: info@artizastudio.de) of your decision to withdraw from this contract by means of a clear statement (e.g. a letter sent by post or an email). You may use the model withdrawal form below, although this is not obligatory.<br><br>To meet the withdrawal deadline, it is sufficient for you to send your communication concerning your exercise of the right of withdrawal before the withdrawal period has expired.',
3),

('widerruf', 's2_heading', 'Section 2 — heading', 'text', '2. Folgen des Widerrufs', '2. Consequences of withdrawal', 4),
('widerruf', 's2_body', 'Section 2 — body', 'textarea',
'Wenn du diesen Vertrag widerrufst, haben wir dir alle Zahlungen, die wir von dir erhalten haben, einschließlich der Lieferkosten (mit Ausnahme der zusätzlichen Kosten, die sich daraus ergeben, dass du eine andere Art der Lieferung als die von uns angebotene, günstigste Standardlieferung gewählt hast), unverzüglich und spätestens binnen vierzehn Tagen ab dem Tag zurückzuzahlen, an dem die Mitteilung über deinen Widerruf dieses Vertrags bei uns eingegangen ist. Für diese Rückzahlung verwenden wir dasselbe Zahlungsmittel, das du bei der ursprünglichen Transaktion eingesetzt hast, es sei denn, mit dir wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden dir wegen dieser Rückzahlung Entgelte berechnet.<br><br>Wir können die Rückzahlung verweigern, bis wir die Waren wieder zurückerhalten haben oder bis du den Nachweis erbracht hast, dass du die Waren zurückgesandt hast, je nachdem, welches der frühere Zeitpunkt ist.<br><br>Du hast die Waren unverzüglich und in jedem Fall spätestens binnen vierzehn Tagen ab dem Tag, an dem du uns über den Widerruf dieses Vertrags unterrichtest, an uns zurückzusenden. Die Frist ist gewahrt, wenn du die Waren vor Ablauf der Frist von vierzehn Tagen absendest.<br><br>Du trägst die unmittelbaren Kosten der Rücksendung der Waren.<br><br>Du musst für einen etwaigen Wertverlust der Waren nur aufkommen, wenn dieser Wertverlust auf einen zur Prüfung der Beschaffenheit, Eigenschaften und Funktionsweise der Waren nicht notwendigen Umgang mit ihnen zurückzuführen ist.',
'If you withdraw from this contract, we will reimburse all payments received from you, including delivery costs (except for the supplementary costs arising if you chose a type of delivery other than the least expensive standard delivery offered by us), without undue delay and at the latest within fourteen days from the day on which we received notification of your withdrawal. We will use the same means of payment you used for the original transaction, unless expressly agreed otherwise; in no event will you be charged any fees for this reimbursement.<br><br>We may withhold reimbursement until we have received the goods back, or until you have supplied evidence of having sent back the goods, whichever is earlier.<br><br>You must return the goods without undue delay and in any event no later than fourteen days from the day on which you inform us of the withdrawal. The deadline is met if you send the goods before the period of fourteen days has expired.<br><br>You bear the direct cost of returning the goods.<br><br>You are only liable for any diminished value of the goods resulting from handling other than what is necessary to establish the nature, characteristics, and functioning of the goods.',
4),

('widerruf', 's3_heading', 'Section 3 — heading', 'text', '3. Ausschluss des Widerrufsrechts', '3. Exclusion of the right of withdrawal', 5),
('widerruf', 's3_body', 'Section 3 — body', 'textarea',
'Das Widerrufsrecht besteht nicht bei Verträgen zur Lieferung von Waren, die nicht vorgefertigt sind und für deren Herstellung eine individuelle Auswahl oder Bestimmung durch dich maßgeblich ist oder die eindeutig auf deine persönlichen Bedürfnisse zugeschnitten sind (§&nbsp;312g Abs.&nbsp;2 Nr.&nbsp;1 BGB).<br><br>Das betrifft insbesondere Produkte, die du mit einer individuellen Gravur, einem Namen oder einem persönlichen Text personalisiert hast — zum Beispiel unsere Buchstaben-Gussformen. Für diese Artikel besteht kein Widerrufsrecht, da sie eigens für dich angefertigt werden.<br><br>Alle anderen, nicht personalisierten Artikel kannst du im Rahmen des oben beschriebenen gesetzlichen Widerrufsrechts zurücksenden.',
'The right of withdrawal does not apply to contracts for the supply of goods that are not prefabricated and for the production of which an individual choice or decision by you is decisive, or that are clearly personalized to your specifications.<br><br>This applies in particular to products you have personalized with an individual engraving, name, or personal text — for example, our letter-mold products. There is no right of withdrawal for these items, since they are made specifically for you.<br><br>All other, non-personalized items can be returned under the statutory right of withdrawal described above.',
5),

('widerruf', 's4_heading', 'Section 4 — heading', 'text', '4. Muster-Widerrufsformular', '4. Model withdrawal form', 6),
('widerruf', 's4_body', 'Section 4 — body', 'textarea',
'(Wenn du den Vertrag widerrufen willst, fülle bitte dieses Formular aus und sende es zurück.)<br><br>An:<br>Artiza Studio, Inh. Nithi Prabhanand<br>Hinterbergstr. 17, 65207 Wiesbaden<br>E-Mail: info@artizastudio.de<br><br>Hiermit widerrufe(n) ich/wir (*) den von mir/uns (*) abgeschlossenen Vertrag über den Kauf der folgenden Waren (*)/die Erbringung der folgenden Dienstleistung (*):<br><br>_______________________________________________<br><br>Bestellt am (*)/erhalten am (*): _______________________<br><br>Name des/der Verbraucher(s):<br><br>_______________________________________________<br><br>Anschrift des/der Verbraucher(s):<br><br>_______________________________________________<br><br>Unterschrift des/der Verbraucher(s) (nur bei Mitteilung auf Papier):<br><br>_______________________________________________<br><br>Datum: _______________________<br><br>(*) Unzutreffendes streichen.',
'(If you want to withdraw from the contract, please fill out this form and send it back.)<br><br>To:<br>Artiza Studio, owner Nithi Prabhanand<br>Hinterbergstr. 17, 65207 Wiesbaden, Germany<br>Email: info@artizastudio.de<br><br>I/we (*) hereby give notice that I/we (*) withdraw from my/our (*) contract of sale of the following goods (*)/for the provision of the following service (*):<br><br>_______________________________________________<br><br>Ordered on (*)/received on (*): _______________________<br><br>Name of consumer(s):<br><br>_______________________________________________<br><br>Address of consumer(s):<br><br>_______________________________________________<br><br>Signature of consumer(s) (only if this form is notified on paper):<br><br>_______________________________________________<br><br>Date: _______________________<br><br>(*) Delete as appropriate.',
6)

on conflict (page_key, field_key) do nothing;
