-- Run this once in Supabase SQL Editor.
--
-- Adds a full Privacy Policy (Datenschutzerklärung) page, editable via
-- Admin -> Content, same system as your other legal pages. Covers every
-- actual data flow on this site: hosting (Vercel), payments (Stripe),
-- accounts/database (Supabase), email (Resend + Zoho Mail), and analytics
-- (Vercel Web Analytics, consent-gated).
--
-- This is a solid, accurate starting draft — not a substitute for a
-- lawyer's review before you rely on it in production.

insert into site_content (page_key, field_key, label, field_type, value_de, value_en, sort_order) values
  ('privacy', 'eyebrow', 'Small label above the title', 'text', 'Rechtliches', 'Legal', 1),
  ('privacy', 'title', 'Page title', 'text', 'Datenschutzerklärung', 'Privacy Policy', 2),
  ('privacy', 's1_heading', 'Section 1 — heading', 'text', '1. Verantwortlicher', '1. Data controller', 3),
  ('privacy', 's1_body', 'Section 1 — body', 'textarea', 'Verantwortlich für die Datenverarbeitung auf dieser Website ist der Betreiber von Artiza Studio. Die vollständigen Kontaktdaten findest du in unserem Impressum.', 'The operator of Artiza Studio is responsible for data processing on this website. Full contact details are available on our Legal Notice (Impressum) page.', 4),
  ('privacy', 's2_heading', 'Section 2 — heading', 'text', '2. Datenerfassung beim Hosting', '2. Data collected by our hosting provider', 5),
  ('privacy', 's2_body', 'Section 2 — body', 'textarea', 'Diese Website wird bei Vercel Inc. gehostet. Beim Aufruf der Website erhebt unser Hosting-Anbieter automatisch technische Informationen (sogenannte Server-Logfiles), z. B. IP-Adresse, Datum und Uhrzeit des Zugriffs, aufgerufene Seite und verwendeter Browser. Diese Daten sind technisch erforderlich, um dir die Website anzuzeigen, und werden nicht mit anderen Datenquellen zusammengeführt.', 'This website is hosted by Vercel Inc. When you visit the site, our hosting provider automatically collects technical information (server log files) such as IP address, date and time of access, the page requested, and browser used. This data is technically required to serve you the site and is not combined with other data sources.', 6),
  ('privacy', 's3_heading', 'Section 3 — heading', 'text', '3. Cookies', '3. Cookies', 7),
  ('privacy', 's3_body', 'Section 3 — body', 'textarea', 'Diese Website verwendet Cookies — sowohl technisch notwendige als auch optionale, die nur mit deiner Zustimmung aktiv werden. Details zu den einzelnen Cookies, ihrem Zweck und wie du deine Auswahl änderst, findest du in unserer <a href="/cookies">Cookie-Richtlinie</a>.', 'This website uses cookies — both technically necessary ones and optional ones that only activate with your consent. For details on individual cookies, their purpose, and how to change your preferences, see our <a href="/cookies">Cookie Policy</a>.', 8),
  ('privacy', 's4_heading', 'Section 4 — heading', 'text', '4. Kontaktformular', '4. Contact form', 9),
  ('privacy', 's4_body', 'Section 4 — body', 'textarea', 'Wenn du uns über das Kontaktformular schreibst, verarbeiten wir die von dir angegebenen Daten (Name, E-Mail-Adresse, Nachricht) ausschließlich zur Bearbeitung deiner Anfrage. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO (vorvertragliche Anfrage) bzw. Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an der Beantwortung von Anfragen).', 'If you contact us through the contact form, we process the information you provide (name, email address, message) solely to handle your inquiry. The legal basis is Art. 6(1)(b) GDPR (pre-contractual inquiry) or Art. 6(1)(f) GDPR (legitimate interest in responding to inquiries).', 10),
  ('privacy', 's5_heading', 'Section 5 — heading', 'text', '5. Kundenkonto und Anmeldung', '5. Customer accounts and login', 11),
  ('privacy', 's5_body', 'Section 5 — body', 'textarea', 'Wenn du ein Konto erstellst, speichern wir deine E-Mail-Adresse und die zugehörigen Bestelldaten, damit du deine Bestellhistorie einsehen kannst. Die Verwaltung von Konten und Anmeldedaten erfolgt über unseren Datenbank- und Authentifizierungs-Dienstleister Supabase. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO (Vertragserfüllung).', 'If you create an account, we store your email address and associated order data so you can view your order history. Account and login management is handled by our database and authentication provider, Supabase. The legal basis is Art. 6(1)(b) GDPR (contract fulfillment).', 12),
  ('privacy', 's6_heading', 'Section 6 — heading', 'text', '6. Bestellung und Zahlungsabwicklung', '6. Orders and payment processing', 13),
  ('privacy', 's6_body', 'Section 6 — body', 'textarea', 'Zur Abwicklung deiner Bestellung erheben wir die notwendigen Daten — Name, Lieferadresse, E-Mail-Adresse, Telefonnummer. Die Zahlungsabwicklung erfolgt über unseren Zahlungsdienstleister Stripe. Deine Zahlungsdaten (z. B. Kartendaten) werden ausschließlich von Stripe verarbeitet und laufen nicht über unsere eigenen Server. Weitere Informationen findest du in der <a href="https://stripe.com/de/privacy" target="_blank" rel="noopener noreferrer">Datenschutzerklärung von Stripe</a>. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO (Vertragserfüllung).', 'To process your order, we collect the necessary information — name, shipping address, email address, phone number. Payment is processed by our payment provider, Stripe. Your payment details (e.g. card information) are handled exclusively by Stripe and never pass through our own servers. See Stripe''s privacy policy for further information. The legal basis is Art. 6(1)(b) GDPR (contract fulfillment).', 14),
  ('privacy', 's7_heading', 'Section 7 — heading', 'text', '7. Rechnungsstellung und Aufbewahrungspflichten', '7. Invoicing and retention obligations', 15),
  ('privacy', 's7_body', 'Section 7 — body', 'textarea', 'Für jede Bestellung erstellen wir eine Rechnung mit den gesetzlich vorgeschriebenen Angaben. Rechnungen unterliegen der gesetzlichen Aufbewahrungspflicht von 10 Jahren (§ 147 AO) und werden entsprechend so lange gespeichert, auch wenn ein Kundenkonto zwischenzeitlich gelöscht wird.', 'We issue an invoice with all legally required details for every order. Invoices are subject to a legal retention requirement of 10 years (§147 AO, German tax code) and are kept for that period accordingly, even if a customer account is deleted in the meantime.', 16),
  ('privacy', 's8_heading', 'Section 8 — heading', 'text', '8. E-Mail-Kommunikation', '8. Email communication', 17),
  ('privacy', 's8_body', 'Section 8 — body', 'textarea', 'Automatisierte E-Mails (z. B. Bestellbestätigungen) versenden wir über den E-Mail-Dienstleister Resend. Unser eigenes geschäftliches Postfach wird über Zoho Mail betrieben. Beide Anbieter verarbeiten die für den Versand notwendigen Daten (E-Mail-Adresse, Inhalt der Nachricht) in unserem Auftrag.', 'Automated emails (such as order confirmations) are sent via our email provider, Resend. Our own business inbox is operated through Zoho Mail. Both providers process the data necessary for delivery (email address, message content) on our behalf.', 18),
  ('privacy', 's9_heading', 'Section 9 — heading', 'text', '9. Webanalyse', '9. Web analytics', 19),
  ('privacy', 's9_body', 'Section 9 — body', 'textarea', 'Mit deiner Zustimmung nutzen wir Vercel Web Analytics zur anonymisierten Auswertung der Websitenutzung. Dieser Dienst setzt keine Cookies und erstellt keine personenbezogenen Nutzungsprofile. Die Verarbeitung erfolgt nur, wenn du der Kategorie „Statistik“ in unserem Cookie-Banner zugestimmt hast, und kann dort jederzeit widerrufen werden.', 'With your consent, we use Vercel Web Analytics to understand site usage in aggregate, anonymized form. This service does not set cookies and does not build personal usage profiles. It only runs if you''ve consented to the "Statistics" category in our cookie banner, which you can withdraw at any time.', 20),
  ('privacy', 's10_heading', 'Section 10 — heading', 'text', '10. Speicherdauer', '10. Retention period', 21),
  ('privacy', 's10_body', 'Section 10 — body', 'textarea', 'Wir speichern personenbezogene Daten nur so lange, wie es für den jeweiligen Zweck erforderlich ist oder gesetzliche Aufbewahrungspflichten dies vorschreiben (z. B. 10 Jahre für Rechnungen). Kontaktanfragen löschen wir, sobald sie abschließend bearbeitet sind und keine Aufbewahrungspflicht mehr besteht.', 'We keep personal data only as long as necessary for its purpose, or as required by law (e.g. 10 years for invoices). Contact inquiries are deleted once fully resolved and no retention obligation applies.', 22),
  ('privacy', 's11_heading', 'Section 11 — heading', 'text', '11. Deine Rechte', '11. Your rights', 23),
  ('privacy', 's11_body', 'Section 11 — body', 'textarea', 'Du hast jederzeit das Recht auf Auskunft über die zu deiner Person gespeicherten Daten, auf Berichtigung, Löschung oder Einschränkung der Verarbeitung, auf Datenübertragbarkeit sowie das Recht, eine erteilte Einwilligung jederzeit zu widerrufen. Außerdem hast du das Recht, dich bei einer Datenschutz-Aufsichtsbehörde zu beschweren, wenn du der Ansicht bist, dass die Verarbeitung deiner Daten gegen die DSGVO verstößt.', 'You have the right at any time to request access to the data we hold about you, to correction, deletion, or restriction of processing, to data portability, and to withdraw any consent you''ve given. You also have the right to lodge a complaint with a data protection supervisory authority if you believe our processing of your data violates the GDPR.', 24),
  ('privacy', 's12_heading', 'Section 12 — heading', 'text', '12. Änderungen dieser Datenschutzerklärung', '12. Changes to this policy', 25),
  ('privacy', 's12_body', 'Section 12 — body', 'textarea', 'Wir passen diese Datenschutzerklärung an, sobald sich die rechtlichen Rahmenbedingungen oder unsere Datenverarbeitung ändern. Es gilt jeweils die aktuell auf dieser Seite veröffentlichte Fassung.', 'We update this privacy policy whenever our legal obligations or data processing practices change. The version currently published on this page is the one that applies.', 26)
on conflict (page_key, field_key) do nothing;
